rm -r ../webservice/gbp/* ;
mkdir ../webservice/gbp/ENA; cp -rp ../shell/skel/new_gbp/* ../webservice/gbp/ENA/;
mkdir ../webservice/gbp/CBOL; cp -rp ../shell/skel/new_gbp/* ../webservice/gbp/CBOL/;
mkdir ../webservice/gbp/GBIF; cp -rp ../shell/skel/new_gbp/* ../webservice/gbp/GBIF/;
mkdir ../webservice/gbp/IUCN; cp -rp ../shell/skel/new_gbp/* ../webservice/gbp/IUCN/;
mkdir ../webservice/gbp/Mycobank; cp -rp ../shell/skel/new_gbp/* ../webservice/gbp/Mycobank/;
find ../webservice/gbp -type d -print0 | xargs -0 chmod 777;
 cp -p ../shell/skel/new_gbp/.htaccess ../webservice/gbp/ENA/;
 cp -p ../shell/skel/new_gbp/.htaccess ../webservice/gbp/CBOL/;
 cp -p ../shell/skel/new_gbp/.htaccess ../webservice/gbp/GBIF/;
 cp -p ../shell/skel/new_gbp/.htaccess ../webservice/gbp/IUCN/;
 cp -p ../shell/skel/new_gbp/.htaccess ../webservice/gbp/Mycobank/;
