USE pipeline;
INSERT INTO pipeline.3i_Cicadellinae SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%3i_Cicadellinae%";
INSERT INTO pipeline.3i_Typhlocybinae SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%3i_Typhlocybinae%";
INSERT INTO pipeline.AFD_Pulmonata SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%AFD_Pulmonata%";
INSERT INTO pipeline.AlgaeBase SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%AlgaeBase%";
INSERT INTO pipeline.AnnonBase SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%AnnonBase%";
INSERT INTO pipeline.AphidSF SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%AphidSF%";
INSERT INTO pipeline.BIOS SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%BIOS%";
INSERT INTO pipeline.BdelloideaBase SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%BdelloideaBase%";
INSERT INTO pipeline.BlattodeaSF SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%BlattodeaSF%";
INSERT INTO pipeline.Brassicaceae SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Brassicaceae%";
INSERT INTO pipeline.CCW SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%CCW%";
INSERT INTO pipeline.CIPA SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%CIPA%";
INSERT INTO pipeline.COOL SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%COOL%";
INSERT INTO pipeline.ChenoBase SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%ChenoBase%";
INSERT INTO pipeline.ChiloBase SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%ChiloBase%";
INSERT INTO pipeline.CilCat SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%CilCat%";
INSERT INTO pipeline.Conifer_Database SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Conifer_Database%";
INSERT INTO pipeline.Dothideomycetes SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Dothideomycetes%";
INSERT INTO pipeline.Droseraceae_Database SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Droseraceae_Database%";
INSERT INTO pipeline.ELPT SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%ELPT%";
INSERT INTO pipeline.ETI_WBD_Euphausiacea SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%ETI_WBD_Euphausiacea%";
INSERT INTO pipeline.EbenaBase SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%EbenaBase%";
INSERT INTO pipeline.EmbiopteraSF SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%EmbiopteraSF%";
INSERT INTO pipeline.FLOW SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%FLOW%";
INSERT INTO pipeline.FWCrabs SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%FWCrabs%";
INSERT INTO pipeline.FishBase SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%FishBase%";
INSERT INTO pipeline.GCC SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%GCC%";
INSERT INTO pipeline.GloBIS_GART SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%GloBIS_GART%";
INSERT INTO pipeline.Glomeromycota SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Glomeromycota%";
INSERT INTO pipeline.Hexacorals SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Hexacorals%";
INSERT INTO pipeline.ICTV_MSL SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%ICTV_MSL%";
INSERT INTO pipeline.ILDIS SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%ILDIS%";
INSERT INTO pipeline.IOPI_GPC SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%IOPI_GPC%";
INSERT INTO pipeline.ITIS_Bees SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%ITIS_Bees%";
INSERT INTO pipeline.ITIS_Global SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%ITIS_Global%";
INSERT INTO pipeline.ITIS_Regional SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%ITIS_Regional%";
INSERT INTO pipeline.LDL_Neuropterida SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%LDL_Neuropterida%";
INSERT INTO pipeline.LHD SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%LHD%";
INSERT INTO pipeline.LIAS SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%LIAS%";
INSERT INTO pipeline.LecyPages SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%LecyPages%";
INSERT INTO pipeline.LepIndex SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%LepIndex%";
INSERT INTO pipeline.MBB SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%MBB%";
INSERT INTO pipeline.MELnet SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%MELnet%";
INSERT INTO pipeline.MOST SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%MOST%";
INSERT INTO pipeline.MOWD SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%MOWD%";
INSERT INTO pipeline.MantodeaSF SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%MantodeaSF%";
INSERT INTO pipeline.NZIB SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%NZIB%";
INSERT INTO pipeline.Nomen_eumycetozoa_com SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Nomen_eumycetozoa_com%";
INSERT INTO pipeline.Odonata SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Odonata%";
INSERT INTO pipeline.OlogamasidBase SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%OlogamasidBase%";
INSERT INTO pipeline.OrthopteraSF SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%OrthopteraSF%";
INSERT INTO pipeline.Parhost SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Parhost%";
INSERT INTO pipeline.PhasmidaSF SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%PhasmidaSF%";
INSERT INTO pipeline.Phyllachorales SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Phyllachorales%";
INSERT INTO pipeline.PhytoseiidBase SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%PhytoseiidBase%";
INSERT INTO pipeline.PlecopteraSF SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%PlecopteraSF%";
INSERT INTO pipeline.Psyllist SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Psyllist%";
INSERT INTO pipeline.RJB_Geranium SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%RJB_Geranium%";
INSERT INTO pipeline.RhodacaridBase SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%RhodacaridBase%";
INSERT INTO pipeline.Rhytismatales SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Rhytismatales%";
INSERT INTO pipeline.Rotifera SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Rotifera%";
INSERT INTO pipeline.Saccharomycetes SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Saccharomycetes%";
INSERT INTO pipeline.SalticidDB SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%SalticidDB%";
INSERT INTO pipeline.ScaleNet SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%ScaleNet%";
INSERT INTO pipeline.Scarabs SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Scarabs%";
INSERT INTO pipeline.Solanaceae_Source SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Solanaceae_Source%";
INSERT INTO pipeline.Species_2000_Common_Names SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Species_2000_Common_Names%";
INSERT INTO pipeline.Species_Fungorum SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Species_Fungorum%";
INSERT INTO pipeline.SpidCat_via_ITIS SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%SpidCat_via_ITIS%";
INSERT INTO pipeline.SpmWeb SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%SpmWeb%";
INSERT INTO pipeline.Strepsiptera_Database SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Strepsiptera_Database%";
INSERT INTO pipeline.SysMyr SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%SysMyr%";
INSERT INTO pipeline.Systema_Dipterorum SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Systema_Dipterorum%";
INSERT INTO pipeline.TIGR_Reptiles SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%TIGR_Reptiles%";
INSERT INTO pipeline.TITAN SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%TITAN%";
INSERT INTO pipeline.Taxapad_Ichneumonoidea SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Taxapad_Ichneumonoidea%";
INSERT INTO pipeline.TenuipalpidBase SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%TenuipalpidBase%";
INSERT INTO pipeline.TicksBase SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%TicksBase%";
INSERT INTO pipeline.Tineidae_NHM SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Tineidae_NHM%";
INSERT INTO pipeline.Trichomycetes SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Trichomycetes%";
INSERT INTO pipeline.UCD SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%UCD%";
INSERT INTO pipeline.URMO SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%URMO%";
INSERT INTO pipeline.WCSP SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WCSP%";
INSERT INTO pipeline.WTaxa SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WTaxa%";
INSERT INTO pipeline.WoRMS_Asteroidea SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Asteroidea%";
INSERT INTO pipeline.WoRMS_Bochusacea SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Bochusacea%";
INSERT INTO pipeline.WoRMS_Brachiopoda SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Brachiopoda%";
INSERT INTO pipeline.WoRMS_Brachypoda SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Brachypoda%";
INSERT INTO pipeline.WoRMS_Brachyura SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Brachyura%";
INSERT INTO pipeline.WoRMS_Bryozoa SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Bryozoa%";
INSERT INTO pipeline.WoRMS_Cumacea SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Cumacea%";
INSERT INTO pipeline.WoRMS_Echinoidea SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Echinoidea%";
INSERT INTO pipeline.WoRMS_Holothuroidea SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Holothuroidea%";
INSERT INTO pipeline.WoRMS_Hydrozoa SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Hydrozoa%";
INSERT INTO pipeline.WoRMS_Isopoda SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Isopoda%";
INSERT INTO pipeline.WoRMS_Leptostraca SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Leptostraca%";
INSERT INTO pipeline.WoRMS_Mystacocarida SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Mystacocarida%";
INSERT INTO pipeline.WoRMS_Nemertea SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Nemertea%";
INSERT INTO pipeline.WoRMS_Oligochaeta SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Oligochaeta%";
INSERT INTO pipeline.WoRMS_Ophiuroidea SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Ophiuroidea%";
INSERT INTO pipeline.WoRMS_Phoronida SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Phoronida%";
INSERT INTO pipeline.WoRMS_Polychaeta SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Polychaeta%";
INSERT INTO pipeline.WoRMS_Polycystina SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Polycystina%";
INSERT INTO pipeline.WoRMS_Porifera SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Porifera%";
INSERT INTO pipeline.WoRMS_Proseriata_Kalyptorhynchia SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Proseriata_Kalyptorhynchia%";
INSERT INTO pipeline.WoRMS_Remipedia SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Remipedia%";
INSERT INTO pipeline.WoRMS_Scaphopoda SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Scaphopoda%";
INSERT INTO pipeline.WoRMS_Tanaidacea SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Tanaidacea%";
INSERT INTO pipeline.WoRMS_Tantulocarida SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Tantulocarida%";
INSERT INTO pipeline.WoRMS_Thermosbaenacea SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Thermosbaenacea%";
INSERT INTO pipeline.WoRMS_Xenoturbellida SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%WoRMS_Xenoturbellida%";
INSERT INTO pipeline.World_Gracillariidae SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%World_Gracillariidae%";
INSERT INTO pipeline.World_Umbellifer_Database SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%World_Umbellifer_Database%";
INSERT INTO pipeline.Xylariaceae SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Xylariaceae%";
INSERT INTO pipeline.ZOBODAT_Vespoidea SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%ZOBODAT_Vespoidea%";
INSERT INTO pipeline.Zygomycetes SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name LIKE "%Zygomycetes%";
INSERT INTO pipeline.protoGSD SELECT `id`, `taxonID`, `genus`, `specificEpithet`, `scientificNameAuthorship`, `infraspecificEpithet`, `verbatimTaxonRank`, `taxonomicStatus`, `acceptedNameUsageID`, `parentNameUsageID`, `family`, `order`, `class`, `phylum`, `kingdom`, `higherClassification`, `namePublishedIn`, `taxonRemarks`, `source`, `updated`, `u`.`username`, `gsd_comments`, `gsd_comments_predefined`, `gsd_short_name`, `gsd_status`, `history_status`, `history_comments`, `tag`, `scientificName`, `taxonRank`, `matched_by` \
FROM piping.taxa pt LEFT JOIN piping.`user` u ON pt.provider_id = `u`.`userid` WHERE gsd_short_name = "protoGSD";
