CREATE TABLE `taxa_new` ( `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
 `taxonID` varchar(12) COLLATE utf8_bin DEFAULT NULL,
 `genus` varchar(255) COLLATE utf8_general_ci NOT NULL,
 `specificEpithet` varchar(255) COLLATE utf8_general_ci NOT NULL,
 `scientificNameAuthorship` varchar(255) COLLATE utf8_general_ci DEFAULT NULL,
 `infraspecificEpithet` varchar(255) COLLATE utf8_general_ci DEFAULT NULL,
 `verbatimTaxonRank` varchar(12) COLLATE utf8_general_ci DEFAULT NULL,
 `taxonomicStatus` varchar(45) COLLATE utf8_general_ci DEFAULT NULL,
 `acceptedNameUsageID` varchar(12) COLLATE utf8_bin DEFAULT NULL,
 `parentNameUsageID` varchar(12) COLLATE utf8_bin DEFAULT NULL,
 `family` varchar(255) COLLATE utf8_general_ci DEFAULT NULL,
 `order` varchar(255) COLLATE utf8_general_ci DEFAULT NULL,
 `class` varchar(255) COLLATE utf8_general_ci DEFAULT NULL,
 `phylum` varchar(255) COLLATE utf8_general_ci DEFAULT NULL,
 `kingdom` varchar(255) COLLATE utf8_general_ci DEFAULT NULL,
 `higherClassification` varchar(500) COLLATE utf8_general_ci DEFAULT NULL,
 `namePublishedIn` varchar(500) COLLATE utf8_general_ci DEFAULT NULL,
 `taxonRemarks` varchar(500) COLLATE utf8_general_ci DEFAULT NULL,
 `source` varchar(255) COLLATE utf8_general_ci DEFAULT NULL,
 `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `provider_id` tinyint(3) unsigned NOT NULL,
 `gsd_comments` varchar(500) COLLATE utf8_general_ci DEFAULT NULL,
 `gsd_comments_predefined` enum("comment1", "comment2", "comment3") COLLATE utf8_general_ci DEFAULT NULL,
 `gsd_short_name` varchar(150) COLLATE utf8_general_ci DEFAULT NULL,
 `gsd_status` varchar(10) DEFAULT NULL,
 `history_status` int(10) DEFAULT NULL,
 `history_comments` varchar(255) COLLATE utf8_general_ci DEFAULT NULL,
 `tag` varchar(32) COLLATE utf8_bin NOT NULL,
 `scientificName` varchar(255) COLLATE utf8_general_ci DEFAULT NULL,
 `taxonRank` varchar(24) COLLATE utf8_general_ci DEFAULT NULL,
 `in_col` tinyint(1) unsigned DEFAULT NULL,
 `matched_by` varchar(8) COLLATE utf8_general_ci DEFAULT NULL,
 PRIMARY KEY (`id`), KEY `scientificName10` (`scientificName`(10)), KEY `genera` (`genus`), KEY `families` (`family`), KEY `orders` (`order`), KEY `classes` (`class`), KEY `phyla` (`phylum`) ) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;


